language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-dist
  - mysql -uroot -e "DROP DATABASE IF EXISTS cake_notifications_test; CREATE DATABASE cake_notifications_test;"

script:
  - composer check

after_success:
  - bash <(curl -s https://codecov.io/bash)